"""
Django settings for advanced_api_project.
Generated by 'django-admin startproject'
"""

from pathlib import Path

# BASE DIR
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'replace-this-with-your-real-secret-key'

# SECURITY WARNING: don't run with debug turned off in production!
DEBUG = True

ALLOWED_HOSTS = []


# ----------------------------------------
# INSTALLED APPS
# ----------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'django_filters',

    # Your app
    'api',
]


# ----------------------------------------
# MIDDLEWARE
# ----------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ----------------------------------------
# URL CONFIG
# ----------------------------------------
ROOT_URLCONF = 'advanced_api_project.urls'


# ----------------------------------------
# TEMPLATES
# ----------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],             # keep empty (default)
        'APP_DIRS': True,       # load templates from installed apps
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ----------------------------------------
# WSGI APP
# ----------------------------------------
WSGI_APPLICATION = 'advanced_api_project.wsgi.application'



# ----------------------------------------
# DATABASE (default sqlite3)
# ----------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ----------------------------------------
# PASSWORD VALIDATION
# ----------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ----------------------------------------
# INTERNATIONALIZATION
# ----------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ----------------------------------------
# STATIC FILES
# ----------------------------------------
STATIC_URL = 'static/'


# ----------------------------------------
# DEFAULT PRIMARY KEY FIELD TYPE
# ----------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# ============================================================
# 🔥 DJANGO REST FRAMEWORK CONFIG (required for ALX Task 2)
# ============================================================

REST_FRAMEWORK = {
    # Enable filtering/searching/ordering
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],

    # 🔥 FIX THE TEMPLATE ERROR
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',           # JSON only
        'rest_framework.renderers.BrowsableAPIRenderer',   # Browsable API (no filter form)
    ],
    

}

# Disable the filter form that caused the template error
DJANGO_FILTERS_DISABLE_HELP_TEXT = True
